[package]
name = "common"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio-websockets = { workspace = true }
