name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt update
      - run: sudo apt install musl musl-dev

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - uses: extractions/setup-just@v3

      - name: install cargo-deb
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deb

      - run: just build-deb-package

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: target/x86_64-unknown-linux-musl/debian/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
